// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikCV-6QnJobL8W5OvvQRT34SQdwQU8BE',
    appId: '1:36316012561:web:04a7404e03ebd9db3291b0',
    messagingSenderId: '36316012561',
    projectId: 'cheng-eng',
    authDomain: 'cheng-eng.firebaseapp.com',
    storageBucket: 'cheng-eng.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJRsIiAIQx8_zk5B0b1honLcFdiI3o5M',
    appId: '1:36316012561:android:b26a02223ffc038a3291b0',
    messagingSenderId: '36316012561',
    projectId: 'cheng-eng',
    storageBucket: 'cheng-eng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjva9GRkCKz7MtcffwwGs2UICrp_Skong',
    appId: '1:36316012561:ios:b3d0152215ffa4113291b0',
    messagingSenderId: '36316012561',
    projectId: 'cheng-eng',
    storageBucket: 'cheng-eng.firebasestorage.app',
    iosBundleId: 'com.example.chengEng3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDikCV-6QnJobL8W5OvvQRT34SQdwQU8BE',
    appId: '1:36316012561:web:c5affea28d1b4b7c3291b0',
    messagingSenderId: '36316012561',
    projectId: 'cheng-eng',
    authDomain: 'cheng-eng.firebaseapp.com',
    storageBucket: 'cheng-eng.firebasestorage.app',
  );
}
